### ISSUE TITLE
Async support for neovim

### ISSUE THREAD

**Issue by james9909** [artur-shaik/vim-javacomplete2#163]
Currently, this plugin is slow on first startup, and lags a little bit when running the completion. Would there be any way to run in the background as to not interfere with the user's workflow? I know neovim features [job control](https://neovim.io/doc/user/job_control.html), and it would be really cool if this could be implemented.

**Comment by brcolow** [comment]
:+1:

**Comment by DonnieWest** [comment]
I'm not sure how feasible that would be given that we're mostly Vimscript, but the low hanging fruit here would be to implement a deoplete source

An example is here https://github.com/racer-rust/vim-racer/blob/master/rplugin/python3/deoplete/sources/racer.py should anyone wish to tackle it

**Comment by wsdjeg** [comment]
deoplete had omni source ,no need to add

**Comment by wsdjeg** [comment]
now i am using deoplete it works very well,and vim start up slow is due to JC2 need detect classpath,and if the classpath file has been generated into ~/.javacomplete2,and you config file has not changed ,the next time will be fast!by the way ,i am using neovim,JC2 also works well,most of people I known has not changed to neovim,so maybe it is not time to use async support!

**Comment by wsdjeg** [comment]
if you use deoplete ,as deoplete is async,you will not be sopped when first time us omni source!

**Comment by wsdjeg** [comment]
here is my vimrc https://github.com/wsdjeg/DotFiles/blob/master/vimrc
you can have a look at the config of deoplete

**Comment by brcolow** [comment]
@wsdjeg James is suggesting using Neovim's async power for JC2 detecting the classpath, compiling Javavi (for first time), etc.

**Comment by wsdjeg** [comment]
i am sorry to misunderstand

**Comment by wsdjeg** [comment]
but the example he given is an source ,the neovim has omni source,and it works well

**Comment by brcolow** [comment]
@wsdjeg No worries. By the way, as a personal suggestion, instead of posting 4 times in a row, why not edit the original post? Yes, half of what he said relates to completion (which could 100% be solved by providing a deoplete omni source, I believe.) The other half "this plugin is slow on first startup" relates more to what I said, if I understand correctly.

**Comment by wsdjeg** [comment]
thanks for your suggestion,i will take it.as i know the author does not use neovim,I'm not sure it will be add into todo list

**Comment by DonnieWest** [comment]
Deoplete will use the omnifunc that java complete provides but is enhanced when you add a "source." For instance, Vim-racer offers both a omnifunc and a source definition for deoplete. Someone might create one if they would use it *shrugs*

**Comment by wsdjeg** [comment]
what is the difference between the "source" and the " omni source "
this is omni source https://github.com/Shougo/deoplete.nvim/blob/master/rplugin/python3/deoplete/sources/omni.py

**Comment by artur-shaik** [comment]
I agree that first completion is slowly enough to get rattled. And I think this can be fixed only with more cache work, that's what I want to do from the beginning. Async caching can be done on java side. So, neovim async can be used for first server compilation and maven/gradle execution.

**Comment by wsdjeg** [comment]
ok I will get more info about neovim async ,and try to improve it

**Comment by wsdjeg** [comment]
i have trid with the neovim jon_control,it is really amazing,the vim will not be deadlock when we start a new job.

**Comment by artur-shaik** [comment]
Made some async caching in `cache` branch. Now if cache is empty, plugin will not block at packages completion, result will be empty.

**Comment by artur-shaik** [comment]
Implemented job_control for server compilation.

**Comment by wsdjeg** [comment]
amazing I will try it tonight

**Comment by wsdjeg** [comment]
@artur-shaik Thanks for implements this feature,it works very well.

**Comment by artur-shaik** [comment]
Yeah, now startup is not so annoying. All that is left is to implement class generation fo gradle.

**Comment by wsdjeg** [comment]
gradle is a letter different with mvn ,as the execable could be `gradle` ,`./gradlew` ,`.\gradle.bat`

**Comment by adelarsq** [comment]
I'm migrating my vim stuff to neovim. Thanks @artur-shaik This helps a lot :+1:

**Comment by wsdjeg** [comment]
@artur-shaik do you use neosnippet and deoplete together with javacomplete2?now I am recording a video about this three plugins ,and I will show why I chooce deoplete instead of YCM. also I think @Shougo will make deoplete and neosnippte more suitable for origin omnifunc complete plugin.
now there are still some issues:
https://github.com/Shougo/neosnippet.vim/issues/322
https://github.com/Shougo/neosnippet.vim/issues/320
https://github.com/Shougo/deoplete.nvim/issues/114#issuecomment-170900572

**Comment by artur-shaik** [comment]
Generation classpath with gradle and job_control done, too.

**Comment by wsdjeg** [comment]
good job!!!

**Comment by artur-shaik** [comment]
As I see, there is no sense to implement deoplete source, because we have all stuff in vimscript. Do I understand right?

**Comment by wsdjeg** [comment]
yes,so i close that PR!

**Comment by wsdjeg** [comment]
the only improvment is faster,you can have a look at deoplete-go

**Comment by artur-shaik** [comment]
I have some strange deoplete completion behavior, seems like it conflict with something. So here I implemented deoplete source file, like `deoplete-go` and `clang-complete`.

https://gist.github.com/artur-shaik/9e1c221059c10d4a9c23#file-javacomplete2-py

@wsdjeg can you try it?

**Comment by wsdjeg** [comment]
ok , but deoplete omni.py source  works well in my os ,can you tell me what is the `strange deoplete completion behavior`

**Comment by wsdjeg** [comment]
@artur-shaik I have finished testting ,this source miss some feature,
1. fuzzy match 
~~2.ignore case~~

**Comment by artur-shaik** [comment]
I will close this. Any news on Deoplete should be in separate issue.

**Comment by wsdjeg** [comment]
ok,let make this source works better
