### ISSUE TITLE
Issues about deoplete source in javacomplete2.

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#246]
### 1. can not fuzzy match after dot.
![2016-05-22-20 36 06](https://cloud.githubusercontent.com/assets/13142418/15453983/37777828-205d-11e6-8fd2-e8ceef9db1ad.png)
![2016-05-22-20 36 12](https://cloud.githubusercontent.com/assets/13142418/15453985/377e5d46-205d-11e6-9c20-69cd344b71bd.png)
![2016-05-22-20 37 44](https://cloud.githubusercontent.com/assets/13142418/15453984/3779c60a-205d-11e6-992b-52a367e956fb.png)

### 2. can not mannuly complete class name
my insert mode <leader><tab> will call this func
```vim
function! MyLeaderTabfunc() abort
    if g:settings.autocomplete_method == 'deoplete'
        return deoplete#mappings#manual_complete(['omni'])
    elseif g:settings.autocomplete_method == 'neocomplete'
        return neocomplete#start_manual_complete(['omni'])
    endif
endfunction
```
type `\<tab>` after `Sys`
manual source omni works well, also support fuzzy match,but javacomplete2 source can not
![2016-05-22-20 41 12](https://cloud.githubusercontent.com/assets/13142418/15454006/de2e97be-205d-11e6-91d6-302f5270ffba.png)
![2016-05-22-20 41 20](https://cloud.githubusercontent.com/assets/13142418/15454007/de345424-205d-11e6-9865-af66990f35c2.png)

### 3 manual source below `@Override`
omni works well, also support fuzzy match
javacomplete2 manual source will show popmenu,but can not fuzzy match

**Comment by artur-shaik** [comment]
I'm not sure how to efficiently it can be implemented to make fuzzy match by jc2. Need more investigation. Will look it, little bit later.

**Comment by artur-shaik** [comment]
Btw, what exactly you expect to match on first three pictures?

**Comment by Eisfreak7** [comment]
I have another problem (not sure if it deserves its own issue, since it is also deoplete related):
With deoplete and javacomplete enabled, javacomplete automatically inserts (not needed) imports while I'm typing.
For example given the following file:
```
public class Test {
    public static void main(String[] args) {
    _
    }
}
```
Where '_' represents the cursor, typing '100' will add the line
'''
import static javafx.beans.binding.Bindings.100;
'''
to the top of the file. This results in a lot of unneeded bindings while typing.

To reproduce, this minimal vimrc (or init.vim) does the trick:
```
call plug#begin('~/.config/nvim/plugged')
Plug 'artur-shaik/vim-javacomplete2', { 'for': 'java' }
Plug 'Shougo/deoplete.nvim'
call plug#end()

let g:deoplete#enable_at_startup = 1
```
(using vim-plug).

Somehow for me this only works if this is copied into the original `init.vim`, if it is another file and neovim is started with `nvim -u minimal.vim Test.java` nothing happens. I'm assuming deoplete depends on the configuration file being called `init.vim`.

**Comment by wsdjeg** [comment]
@artur-shaik Shougo the author of deoplete says he will test for the source. and also I will try to do it.I want javacomete2 source works same as omni source.
on third pic, if I type into `wi`, should show me three `wait()`, same as second pic.

**Comment by artur-shaik** [comment]
@Eisfreak7 I think you shoul check @wsdjeg 's DotFIles for configuring deoplete, I'm not currently use it.

**Comment by wsdjeg** [comment]
@Eisfreak7 it is due to your config about deoplete, I mean, your config make deoplete auto start omni complete after `100`, also you have a class named 100. so it will be auto imported. and please update your deoplete, the latest version of deoplete remove java input_partten init.
BTW, you can see my config about deoplete.
https://github.com/wsdjeg/DotFiles/blob/master/config/nvim/config/plugins/deoplete.vim

**Comment by wsdjeg** [comment]
> calling autocmd! javacomplete to clear all of javacompletes autocmds (I assume the TextChangedI one is responsible) disables this behaviour.

auto import the class is the feature of javacomplete2, the class only be imported when you complete the class name, so you should disable auto complete class name after `100`, instead of disable the javacomplete2's feature.

**Comment by Eisfreak7** [comment]
@artur-shaik @wsdjeg Thank you, for future reference specifically these lines from @wsdjeg's configuartion were needed:
```
let g:deoplete#ignore_sources = {}
let g:deoplete#ignore_sources._ = ['javacomplete2']
```
Maybe it would be a good idea to include these in the readme, since I can imagine I'm not the only one who didn't expect this bevior.

I don't fully understand why this works though. Shouldn't this basically disable the use of javacomplete2 in deoplete? (It doesn't, I still get suggestions from javacomplete).

**Comment by wsdjeg** [comment]
@Eisfreak7 deoplete do not disable the user source, I have asked @Shougo, he and ohther deoplete sources's auther both think we should enable it by default.

BTW, I think we should improve javacomplete2 source instead of disable it.

**Comment by Shougo** [comment]
@wsdjeg I will fix the problem.  Please wait.

**Comment by wsdjeg** [comment]
thanks!
