### ISSUE TITLE
Freezing when complete

### ISSUE THREAD

**Issue by andiderp** [artur-shaik/vim-javacomplete2#57]
Freezes if I want to complete a methodcall.

**Comment by andiderp** [comment]
Ok I think I know why this error happens.
At the top of the file in which I want to use the completion there was a line that looks like this:
import java.io.File; import java.io.FileFilter;
This is legal Java but it freezes.

**Comment by wsdjeg** [comment]
insert it in different line,then have a try

**Comment by pmaziere** [comment]
I don't know about @andiderp freeze, but the one I experience is not fixed by  2ba11b0

I try to edit app/src/main/java/at/bitfire/icsdroid/ui/AddCalendarValidationFragment.java from https://gitlab.com/bitfireAT/icsdroid.git and the only way to avoid the freeze when completing is to comment the "extends DialogFragment" part

**Comment by artur-shaik** [comment]
@pmaziere, please, can you open an issue?
